name: Test

on: [pull_request, push]

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Setup: .NET Core SDK'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: 'Run: Test'
        run: ./build.cmd Test
